language: node_js
node_js:
  - "4.4.3"
  - "5.7.0"

env:
- NODE_ENV=TEST

notifications:
  slack:
    rooms:
      - leighton-obrien:46kCwOi8pOgzeWvLzxJjZfJ2#general
      - leighton-obrien:46kCwOi8pOgzeWvLzxJjZfJ2#component-factory